name: build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - uses: actions/setup-go@v3
      - name: Execute script
        run: |
          chmod +x ./build.sh
          ./build.sh